-- Inventory Platform v2, PostgreSQL network baseline.
--
-- IDs are generated by the Rust application (UUIDv7).  All business rows
-- carry tenant_id and refer to one another through (tenant_id, id), which
-- makes a cross-tenant relation impossible even if an application query is
-- accidentally missing a predicate.  RLS is enabled and forced below.

CREATE SCHEMA IF NOT EXISTS app;

CREATE OR REPLACE FUNCTION app.current_tenant_id()
RETURNS uuid
LANGUAGE sql
STABLE
PARALLEL SAFE
AS $$
    SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid
$$;

CREATE TABLE tenants (
    id uuid PRIMARY KEY,
    slug text NOT NULL CHECK (length(btrim(slug)) > 0),
    name text NOT NULL CHECK (length(btrim(name)) > 0),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (slug)
);

CREATE TABLE workspaces (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    id uuid NOT NULL,
    name text NOT NULL CHECK (length(btrim(name)) > 0),
    timezone text NOT NULL DEFAULT 'Asia/Shanghai',
    source_instance_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, name)
);

CREATE TABLE business_parties (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    id uuid NOT NULL,
    normalized_name text NOT NULL CHECK (length(btrim(normalized_name)) > 0),
    display_name text NOT NULL CHECK (length(btrim(display_name)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, normalized_name)
);

CREATE TABLE party_roles (
    tenant_id uuid NOT NULL,
    party_id uuid NOT NULL,
    role text NOT NULL CHECK (role IN ('goods_owner', 'upstream_receiver', 'supplier', 'carrier')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, party_id, role),
    FOREIGN KEY (tenant_id, party_id)
        REFERENCES business_parties (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE skus (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    id uuid NOT NULL,
    code text NOT NULL CHECK (length(btrim(code)) > 0),
    name text NOT NULL CHECK (length(btrim(name)) > 0),
    tracking_mode text NOT NULL DEFAULT 'serial'
        CHECK (tracking_mode IN ('serial', 'quantity')),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, code)
);

CREATE TABLE warehouses (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    id uuid NOT NULL,
    code text NOT NULL CHECK (length(btrim(code)) > 0),
    name text NOT NULL CHECK (length(btrim(name)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, code)
);

CREATE TABLE locations (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    warehouse_id uuid NOT NULL,
    code text NOT NULL CHECK (length(btrim(code)) > 0),
    name text NOT NULL CHECK (length(btrim(name)) > 0),
    kind text NOT NULL CHECK (kind IN ('receiving', 'storage', 'quarantine', 'shipping')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, warehouse_id, code),
    FOREIGN KEY (tenant_id, warehouse_id)
        REFERENCES warehouses (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE inbound_receipts (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    receipt_no text NOT NULL CHECK (length(btrim(receipt_no)) > 0),
    owner_party_id uuid NOT NULL,
    warehouse_id uuid NOT NULL,
    source_reference text,
    received_at timestamptz NOT NULL,
    status text NOT NULL CHECK (status IN ('draft', 'posted', 'voided')),
    actor_id uuid NOT NULL,
    idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) > 0),
    request_id text NOT NULL CHECK (length(btrim(request_id)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, receipt_no),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, owner_party_id)
        REFERENCES business_parties (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, warehouse_id)
        REFERENCES warehouses (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE inbound_receipt_lines (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    receipt_id uuid NOT NULL,
    sku_id uuid NOT NULL,
    declared_quantity integer NOT NULL CHECK (declared_quantity > 0),
    scanned_quantity integer NOT NULL DEFAULT 0
        CHECK (scanned_quantity >= 0 AND scanned_quantity <= declared_quantity),
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    FOREIGN KEY (tenant_id, receipt_id)
        REFERENCES inbound_receipts (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, sku_id)
        REFERENCES skus (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE inventory_units (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    barcode text NOT NULL CHECK (length(btrim(barcode)) > 0),
    inbound_receipt_line_id uuid NOT NULL,
    owner_party_id uuid NOT NULL,
    sku_id uuid NOT NULL,
    location_id uuid NOT NULL,
    inventory_status text NOT NULL CHECK (inventory_status IN (
        'received', 'available', 'reserved', 'shipped', 'delivered',
        'quarantined', 'scrapped', 'returned_to_owner', 'voided'
    )),
    quality_status text NOT NULL
        CHECK (quality_status IN ('untested', 'testing', 'passed', 'failed', 'waived')),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    received_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, barcode),
    FOREIGN KEY (tenant_id, inbound_receipt_line_id)
        REFERENCES inbound_receipt_lines (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, owner_party_id)
        REFERENCES business_parties (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, sku_id)
        REFERENCES skus (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, location_id)
        REFERENCES locations (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE quality_inspections (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    inspection_no text NOT NULL CHECK (length(btrim(inspection_no)) > 0),
    inspection_type text NOT NULL CHECK (inspection_type IN ('initial', 'retest')),
    status text NOT NULL CHECK (status IN ('in_progress', 'completed', 'voided')),
    inspector_id uuid NOT NULL,
    inspected_at timestamptz NOT NULL,
    idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) > 0),
    request_id text NOT NULL CHECK (length(btrim(request_id)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, inspection_no),
    UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE quality_inspection_results (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    inspection_id uuid NOT NULL,
    inventory_unit_id uuid NOT NULL,
    result text NOT NULL CHECK (result IN ('passed', 'failed')),
    defect_code text,
    measurements_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, inspection_id, inventory_unit_id),
    FOREIGN KEY (tenant_id, inspection_id)
        REFERENCES quality_inspections (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, inventory_unit_id)
        REFERENCES inventory_units (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE quality_waivers (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    inventory_unit_id uuid NOT NULL,
    reason text NOT NULL CHECK (length(btrim(reason)) > 0),
    authorized_by uuid NOT NULL,
    authorized_at timestamptz NOT NULL,
    revoked_at timestamptz,
    PRIMARY KEY (tenant_id, id),
    FOREIGN KEY (tenant_id, inventory_unit_id)
        REFERENCES inventory_units (tenant_id, id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX quality_waivers_one_active_idx
    ON quality_waivers (tenant_id, inventory_unit_id)
    WHERE revoked_at IS NULL;

CREATE TABLE outbound_orders (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    order_no text NOT NULL CHECK (length(btrim(order_no)) > 0),
    upstream_receiver_id uuid NOT NULL,
    required_at timestamptz,
    status text NOT NULL CHECK (status IN (
        'draft', 'open', 'partially_allocated', 'allocated', 'partially_shipped',
        'shipped', 'completed', 'voided'
    )),
    actor_id uuid NOT NULL,
    idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) > 0),
    request_id text NOT NULL CHECK (length(btrim(request_id)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, order_no),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, upstream_receiver_id)
        REFERENCES business_parties (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE outbound_order_lines (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    outbound_order_id uuid NOT NULL,
    sku_id uuid NOT NULL,
    required_quantity integer NOT NULL CHECK (required_quantity > 0),
    allocated_quantity integer NOT NULL DEFAULT 0 CHECK (allocated_quantity >= 0),
    shipped_quantity integer NOT NULL DEFAULT 0 CHECK (shipped_quantity >= 0),
    delivered_quantity integer NOT NULL DEFAULT 0 CHECK (delivered_quantity >= 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    CHECK (
        delivered_quantity <= shipped_quantity
        AND shipped_quantity <= allocated_quantity
        AND allocated_quantity <= required_quantity
    ),
    FOREIGN KEY (tenant_id, outbound_order_id)
        REFERENCES outbound_orders (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, sku_id)
        REFERENCES skus (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE outbound_allocations (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    outbound_order_line_id uuid NOT NULL,
    inventory_unit_id uuid NOT NULL,
    sku_id uuid NOT NULL,
    status text NOT NULL CHECK (status IN ('active', 'released', 'shipped', 'voided')),
    allocated_by uuid NOT NULL,
    allocated_at timestamptz NOT NULL,
    released_at timestamptz,
    PRIMARY KEY (tenant_id, id),
    FOREIGN KEY (tenant_id, outbound_order_line_id)
        REFERENCES outbound_order_lines (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, inventory_unit_id)
        REFERENCES inventory_units (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, sku_id)
        REFERENCES skus (tenant_id, id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX outbound_allocations_one_active_unit_idx
    ON outbound_allocations (tenant_id, inventory_unit_id)
    WHERE status IN ('active', 'shipped');

CREATE TABLE outbound_shipments (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    shipment_no text NOT NULL CHECK (length(btrim(shipment_no)) > 0),
    outbound_order_id uuid NOT NULL,
    status text NOT NULL CHECK (status IN (
        'draft', 'posted', 'partially_delivered', 'delivered', 'voided'
    )),
    shipped_at timestamptz NOT NULL,
    actor_id uuid NOT NULL,
    idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) > 0),
    request_id text NOT NULL CHECK (length(btrim(request_id)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, shipment_no),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, outbound_order_id)
        REFERENCES outbound_orders (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE outbound_shipment_lines (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    outbound_shipment_id uuid NOT NULL,
    outbound_allocation_id uuid NOT NULL,
    inventory_unit_id uuid NOT NULL,
    scanned_barcode_snapshot text NOT NULL CHECK (length(btrim(scanned_barcode_snapshot)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, inventory_unit_id),
    FOREIGN KEY (tenant_id, outbound_shipment_id)
        REFERENCES outbound_shipments (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, outbound_allocation_id)
        REFERENCES outbound_allocations (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, inventory_unit_id)
        REFERENCES inventory_units (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE delivery_confirmations (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    outbound_shipment_id uuid NOT NULL,
    confirmation_code text NOT NULL CHECK (length(btrim(confirmation_code)) > 0),
    confirmed_by uuid NOT NULL,
    confirmed_at timestamptz NOT NULL,
    notes text,
    idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) > 0),
    request_id text NOT NULL CHECK (length(btrim(request_id)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, confirmation_code),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, outbound_shipment_id)
        REFERENCES outbound_shipments (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE delivery_confirmation_lines (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    delivery_confirmation_id uuid NOT NULL,
    outbound_shipment_line_id uuid NOT NULL,
    result text NOT NULL CHECK (result IN ('accepted', 'rejected')),
    exception_notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, outbound_shipment_line_id),
    FOREIGN KEY (tenant_id, delivery_confirmation_id)
        REFERENCES delivery_confirmations (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, outbound_shipment_line_id)
        REFERENCES outbound_shipment_lines (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE outbound_return_batches (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    return_no text NOT NULL CHECK (length(btrim(return_no)) > 0),
    returned_at timestamptz NOT NULL,
    actor_id uuid NOT NULL,
    idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) > 0),
    request_id text NOT NULL CHECK (length(btrim(request_id)) > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, return_no),
    UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE outbound_return_lines (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    return_batch_id uuid NOT NULL,
    outbound_shipment_line_id uuid NOT NULL,
    inventory_unit_id uuid NOT NULL,
    reason text NOT NULL CHECK (length(btrim(reason)) > 0),
    disposition text NOT NULL CHECK (disposition IN ('quarantine', 'returned_to_owner', 'scrapped')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, outbound_shipment_line_id),
    FOREIGN KEY (tenant_id, return_batch_id)
        REFERENCES outbound_return_batches (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, outbound_shipment_line_id)
        REFERENCES outbound_shipment_lines (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, inventory_unit_id)
        REFERENCES inventory_units (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE stock_movements (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    inventory_unit_id uuid NOT NULL,
    movement_type text NOT NULL CHECK (movement_type IN (
        'received', 'moved', 'reserved', 'reservation_released', 'shipped',
        'delivered', 'returned', 'scrapped', 'returned_to_owner', 'voided', 'corrected'
    )),
    from_location_id uuid,
    to_location_id uuid,
    source_type text NOT NULL,
    source_id uuid NOT NULL,
    actor_id uuid NOT NULL,
    occurred_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    FOREIGN KEY (tenant_id, inventory_unit_id)
        REFERENCES inventory_units (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, from_location_id)
        REFERENCES locations (tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, to_location_id)
        REFERENCES locations (tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE audit_logs (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    actor_id uuid,
    action text NOT NULL CHECK (length(btrim(action)) > 0),
    entity_type text NOT NULL CHECK (length(btrim(entity_type)) > 0),
    entity_id uuid NOT NULL,
    request_id text NOT NULL CHECK (length(btrim(request_id)) > 0),
    result text NOT NULL CHECK (result IN ('success', 'rejected')),
    details_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id)
);

CREATE TABLE idempotency_records (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    scope text NOT NULL CHECK (length(btrim(scope)) > 0),
    idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) > 0),
    request_hash text NOT NULL CHECK (length(btrim(request_hash)) > 0),
    response_json jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, scope, idempotency_key)
);

CREATE TABLE migration_packages (
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    export_id text NOT NULL CHECK (length(btrim(export_id)) > 0),
    direction text NOT NULL CHECK (direction IN ('offline_to_network', 'network_to_offline')),
    schema_version integer NOT NULL CHECK (schema_version > 0),
    checksum text NOT NULL CHECK (length(btrim(checksum)) > 0),
    status text NOT NULL CHECK (status IN ('created', 'validated', 'imported', 'failed', 'archived')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    imported_at timestamptz,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, export_id),
    FOREIGN KEY (tenant_id, workspace_id)
        REFERENCES workspaces (tenant_id, id) ON DELETE RESTRICT
);

-- Cross-entity indexes used by inventory lists, traceability and audit views.
CREATE INDEX inventory_units_owner_received_idx
    ON inventory_units (tenant_id, owner_party_id, received_at DESC);
CREATE INDEX inventory_units_sku_status_idx
    ON inventory_units (tenant_id, sku_id, inventory_status, quality_status);
CREATE INDEX inventory_units_receipt_line_idx
    ON inventory_units (tenant_id, inbound_receipt_line_id, id);
CREATE INDEX outbound_orders_receiver_date_idx
    ON outbound_orders (tenant_id, upstream_receiver_id, created_at DESC, id);
CREATE INDEX outbound_allocations_order_status_idx
    ON outbound_allocations (tenant_id, outbound_order_line_id, status);
CREATE INDEX stock_movements_unit_time_idx
    ON stock_movements (tenant_id, inventory_unit_id, occurred_at DESC);
CREATE INDEX audit_logs_actor_time_idx
    ON audit_logs (tenant_id, actor_id, occurred_at DESC);

-- The SKU is intentionally repeated on an allocation so reports can use a
-- covering index.  The trigger keeps that projection consistent with both
-- sides of the allocation relationship.
CREATE OR REPLACE FUNCTION app.validate_allocation_sku()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    line_sku uuid;
    unit_sku uuid;
BEGIN
    SELECT sku_id INTO line_sku
      FROM outbound_order_lines
     WHERE tenant_id = NEW.tenant_id AND id = NEW.outbound_order_line_id;
    SELECT sku_id INTO unit_sku
      FROM inventory_units
     WHERE tenant_id = NEW.tenant_id AND id = NEW.inventory_unit_id;
    IF line_sku IS NULL OR unit_sku IS NULL OR line_sku IS DISTINCT FROM NEW.sku_id
       OR unit_sku IS DISTINCT FROM NEW.sku_id THEN
        RAISE EXCEPTION 'allocation SKU does not match order line and inventory unit'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER outbound_allocations_sku_consistency
    BEFORE INSERT OR UPDATE OF outbound_order_line_id, inventory_unit_id, sku_id
    ON outbound_allocations
    FOR EACH ROW EXECUTE FUNCTION app.validate_allocation_sku();

-- Tenant rows are visible only after the transaction establishes the same
-- tenant context.  Provisioning code should use a dedicated migration/admin
-- role to create the first tenant, then hand ordinary requests to the RLS
-- application role.
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
CREATE POLICY tenants_current_context ON tenants
    USING (id = app.current_tenant_id())
    WITH CHECK (id = app.current_tenant_id());

ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspaces FORCE ROW LEVEL SECURITY;
CREATE POLICY workspaces_current_context ON workspaces
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE business_parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_parties FORCE ROW LEVEL SECURITY;
CREATE POLICY business_parties_current_context ON business_parties
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE party_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_roles FORCE ROW LEVEL SECURITY;
CREATE POLICY party_roles_current_context ON party_roles
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE skus ENABLE ROW LEVEL SECURITY;
ALTER TABLE skus FORCE ROW LEVEL SECURITY;
CREATE POLICY skus_current_context ON skus
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouses FORCE ROW LEVEL SECURITY;
CREATE POLICY warehouses_current_context ON warehouses
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations FORCE ROW LEVEL SECURITY;
CREATE POLICY locations_current_context ON locations
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE inbound_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE inbound_receipts FORCE ROW LEVEL SECURITY;
CREATE POLICY inbound_receipts_current_context ON inbound_receipts
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE inbound_receipt_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE inbound_receipt_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY inbound_receipt_lines_current_context ON inbound_receipt_lines
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE inventory_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_units FORCE ROW LEVEL SECURITY;
CREATE POLICY inventory_units_current_context ON inventory_units
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE quality_inspections ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality_inspections FORCE ROW LEVEL SECURITY;
CREATE POLICY quality_inspections_current_context ON quality_inspections
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE quality_inspection_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality_inspection_results FORCE ROW LEVEL SECURITY;
CREATE POLICY quality_inspection_results_current_context ON quality_inspection_results
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE quality_waivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality_waivers FORCE ROW LEVEL SECURITY;
CREATE POLICY quality_waivers_current_context ON quality_waivers
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE outbound_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_orders FORCE ROW LEVEL SECURITY;
CREATE POLICY outbound_orders_current_context ON outbound_orders
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE outbound_order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_order_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY outbound_order_lines_current_context ON outbound_order_lines
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE outbound_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_allocations FORCE ROW LEVEL SECURITY;
CREATE POLICY outbound_allocations_current_context ON outbound_allocations
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE outbound_shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_shipments FORCE ROW LEVEL SECURITY;
CREATE POLICY outbound_shipments_current_context ON outbound_shipments
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE outbound_shipment_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_shipment_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY outbound_shipment_lines_current_context ON outbound_shipment_lines
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE delivery_confirmations ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_confirmations FORCE ROW LEVEL SECURITY;
CREATE POLICY delivery_confirmations_current_context ON delivery_confirmations
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE delivery_confirmation_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_confirmation_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY delivery_confirmation_lines_current_context ON delivery_confirmation_lines
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE outbound_return_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_return_batches FORCE ROW LEVEL SECURITY;
CREATE POLICY outbound_return_batches_current_context ON outbound_return_batches
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE outbound_return_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_return_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY outbound_return_lines_current_context ON outbound_return_lines
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements FORCE ROW LEVEL SECURITY;
CREATE POLICY stock_movements_current_context ON stock_movements
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_logs_current_context ON audit_logs
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE idempotency_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE idempotency_records FORCE ROW LEVEL SECURITY;
CREATE POLICY idempotency_records_current_context ON idempotency_records
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

ALTER TABLE migration_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE migration_packages FORCE ROW LEVEL SECURITY;
CREATE POLICY migration_packages_current_context ON migration_packages
    USING (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());
